from .not_input_file_dialog import Ui_NotInputFileDialog
from .actualizayion_new_app import Ui_Actualization
from .not_execute_file_dialog import Ui_NotExecuteDialog
from .success_read_dialog import Ui_successfully_read
from .not_founded_for_searc_gialog import Ui_NotFoundedForSearchDialog
from .warning_execute import Ui_Dialog
from . import resoursec_rc