# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/actualization_new_app.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Actualization(object):
    def setupUi(self, Actualization):
        Actualization.setObjectName("Actualization")
        Actualization.resize(864, 566)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/actualization.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Actualization.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(Actualization)
        self.centralwidget.setStyleSheet("* {\n"
"    font-size: 24px;\n"
"    text-align: center;\n"
"    border: 0.5px solid black;\n"
"    border-radius: 10px; \n"
"}\n"
"\n"
"QLabel {\n"
"     qproperty-alignment: AlignCenter; \n"
"    \n"
"}\n"
"\n"
"QTabWidget::pane {\n"
"    top: -1px;\n"
"}\n"
"\n"
"\n"
"QTabWidget::tab-bar {\n"
"    left: 5px;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    color: #bbb;\n"
"    border: 1px solid #444;\n"
"    border-bottom: none;\n"
"    border-top-left-radius: 6px;\n"
"    border-top-right-radius: 6px;\n"
"    padding: 8px 16px;\n"
"    margin-right: 4px;\n"
"}\n"
"\n"
"QTabBar::tab:hover {\n"
"    background: rgba(16, 67, 188, 255);\n"
"    color: #fff;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background: rgba(8, 4, 188, 255);\n"
"    color: #fff;\n"
"    margin-bottom: -1px;\n"
"}\n"
"\n"
"QTabBar::tab:!selected {\n"
"    margin-top: 1px;\n"
"}\n"
"\n"
"QWidget {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(8, 4, 188, 255), stop:1 rgba(24, 129, 187, 255));\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: rgba(16, 67, 188, 255);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: rgba(8, 4, 188, 255);\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"        background-color: #2e3f6e;\n"
"        color: white;\n"
"        font-weight: bold;\n"
"        padding: 4px;\n"
"        border: 1px solid #6c6c6c;\n"
"    }")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setToolTip("")
        self.tabWidget.setObjectName("tabWidget")
        self.reading_file_tab = QtWidgets.QWidget()
        self.reading_file_tab.setObjectName("reading_file_tab")
        self.gridLayout = QtWidgets.QGridLayout(self.reading_file_tab)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.title_lbl = QtWidgets.QLabel(self.reading_file_tab)
        self.title_lbl.setObjectName("title_lbl")
        self.gridLayout_2.addWidget(self.title_lbl, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.input_file_btn = QtWidgets.QPushButton(self.reading_file_tab)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/ChooseItem.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.input_file_btn.setIcon(icon1)
        self.input_file_btn.setIconSize(QtCore.QSize(32, 32))
        self.input_file_btn.setObjectName("input_file_btn")
        self.horizontalLayout.addWidget(self.input_file_btn)
        self.clear_btn = QtWidgets.QPushButton(self.reading_file_tab)
        self.clear_btn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/TrashCan.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.clear_btn.setIcon(icon2)
        self.clear_btn.setIconSize(QtCore.QSize(32, 32))
        self.clear_btn.setObjectName("clear_btn")
        self.horizontalLayout.addWidget(self.clear_btn)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.selected_file_lbl = QtWidgets.QLabel(self.reading_file_tab)
        self.selected_file_lbl.setText("")
        self.selected_file_lbl.setObjectName("selected_file_lbl")
        self.verticalLayout_3.addWidget(self.selected_file_lbl)
        self.run_btn = QtWidgets.QPushButton(self.reading_file_tab)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/TriangleRight.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.run_btn.setIcon(icon3)
        self.run_btn.setIconSize(QtCore.QSize(32, 32))
        self.run_btn.setObjectName("run_btn")
        self.verticalLayout_3.addWidget(self.run_btn)
        self.verticalLayout_5.addLayout(self.verticalLayout_3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.founded_lbl = QtWidgets.QLabel(self.reading_file_tab)
        self.founded_lbl.setObjectName("founded_lbl")
        self.verticalLayout_6.addWidget(self.founded_lbl)
        self.founded_list = QtWidgets.QListWidget(self.reading_file_tab)
        self.founded_list.setObjectName("founded_list")
        self.verticalLayout_6.addWidget(self.founded_list)
        self.save_btn = QtWidgets.QPushButton(self.reading_file_tab)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/SaveFilled.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.save_btn.setIcon(icon4)
        self.save_btn.setIconSize(QtCore.QSize(32, 32))
        self.save_btn.setObjectName("save_btn")
        self.verticalLayout_6.addWidget(self.save_btn)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.reading_file_tab, "")
        self.selenium_tab = QtWidgets.QWidget()
        self.selenium_tab.setObjectName("selenium_tab")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.selenium_tab)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.radio_group = QtWidgets.QGroupBox(self.selenium_tab)
        self.radio_group.setTitle("")
        self.radio_group.setObjectName("radio_group")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.radio_group)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.search_radio_btn = QtWidgets.QRadioButton(self.radio_group)
        self.search_radio_btn.setChecked(True)
        self.search_radio_btn.setObjectName("search_radio_btn")
        self.verticalLayout_2.addWidget(self.search_radio_btn)
        self.file_radio_btn = QtWidgets.QRadioButton(self.radio_group)
        self.file_radio_btn.setObjectName("file_radio_btn")
        self.verticalLayout_2.addWidget(self.file_radio_btn)
        self.gridLayout_4.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.verticalLayout_9.addWidget(self.radio_group)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.widget_group = QtWidgets.QGroupBox(self.selenium_tab)
        self.widget_group.setTitle("")
        self.widget_group.setObjectName("widget_group")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.widget_group)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.list_group = QtWidgets.QGroupBox(self.widget_group)
        self.list_group.setTitle("")
        self.list_group.setObjectName("list_group")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.list_group)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.founded_list_widget = QtWidgets.QListWidget(self.list_group)
        self.founded_list_widget.setObjectName("founded_list_widget")
        self.gridLayout_5.addWidget(self.founded_list_widget, 0, 0, 1, 1)
        self.verticalLayout_7.addWidget(self.list_group)
        self.choose_group = QtWidgets.QGroupBox(self.widget_group)
        self.choose_group.setEnabled(True)
        self.choose_group.setTitle("")
        self.choose_group.setObjectName("choose_group")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.choose_group)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.choose_btn = QtWidgets.QPushButton(self.choose_group)
        self.choose_btn.setIcon(icon1)
        self.choose_btn.setIconSize(QtCore.QSize(30, 30))
        self.choose_btn.setObjectName("choose_btn")
        self.horizontalLayout_3.addWidget(self.choose_btn)
        self.delete_btn = QtWidgets.QPushButton(self.choose_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delete_btn.sizePolicy().hasHeightForWidth())
        self.delete_btn.setSizePolicy(sizePolicy)
        self.delete_btn.setMinimumSize(QtCore.QSize(30, 32))
        self.delete_btn.setText("")
        self.delete_btn.setIcon(icon2)
        self.delete_btn.setIconSize(QtCore.QSize(30, 30))
        self.delete_btn.setObjectName("delete_btn")
        self.horizontalLayout_3.addWidget(self.delete_btn)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.choose_lbl = QtWidgets.QLabel(self.choose_group)
        self.choose_lbl.setText("")
        self.choose_lbl.setObjectName("choose_lbl")
        self.verticalLayout_4.addWidget(self.choose_lbl)
        self.gridLayout_3.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.run_read_btn = QtWidgets.QPushButton(self.choose_group)
        self.run_read_btn.setIcon(icon3)
        self.run_read_btn.setIconSize(QtCore.QSize(30, 30))
        self.run_read_btn.setObjectName("run_read_btn")
        self.gridLayout_3.addWidget(self.run_read_btn, 1, 0, 1, 1)
        self.verticalLayout_7.addWidget(self.choose_group)
        self.gridLayout_6.addLayout(self.verticalLayout_7, 0, 0, 1, 1)
        self.verticalLayout_8.addWidget(self.widget_group)
        self.run_btn_2 = QtWidgets.QPushButton(self.selenium_tab)
        self.run_btn_2.setIcon(icon3)
        self.run_btn_2.setIconSize(QtCore.QSize(30, 30))
        self.run_btn_2.setObjectName("run_btn_2")
        self.verticalLayout_8.addWidget(self.run_btn_2)
        self.verticalLayout_9.addLayout(self.verticalLayout_8)
        self.horizontalLayout_4.addLayout(self.verticalLayout_9)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_2 = QtWidgets.QLabel(self.selenium_tab)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_10.addWidget(self.label_2)
        self.result_table_view = QtWidgets.QTableView(self.selenium_tab)
        self.result_table_view.setObjectName("result_table_view")
        self.verticalLayout_10.addWidget(self.result_table_view)
        self.save_serch_btn = QtWidgets.QPushButton(self.selenium_tab)
        self.save_serch_btn.setIcon(icon4)
        self.save_serch_btn.setIconSize(QtCore.QSize(30, 30))
        self.save_serch_btn.setObjectName("save_serch_btn")
        self.verticalLayout_10.addWidget(self.save_serch_btn)
        self.horizontalLayout_4.addLayout(self.verticalLayout_10)
        self.gridLayout_7.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.tabWidget.addTab(self.selenium_tab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        Actualization.setCentralWidget(self.centralwidget)

        self.retranslateUi(Actualization)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Actualization)

    def retranslateUi(self, Actualization):
        _translate = QtCore.QCoreApplication.translate
        Actualization.setWindowTitle(_translate("Actualization", "Actualization"))
        self.reading_file_tab.setToolTip(_translate("Actualization", "Вкладка для нахождения ГОСТов из файла"))
        self.title_lbl.setText(_translate("Actualization", "Чтение ГОСТов из файла"))
        self.input_file_btn.setToolTip(_translate("Actualization", "Выбрать файл для чтения"))
        self.input_file_btn.setText(_translate("Actualization", "Выберите файл"))
        self.input_file_btn.setShortcut(_translate("Actualization", "Ctrl+F"))
        self.clear_btn.setToolTip(_translate("Actualization", "Отменить выбор файла"))
        self.clear_btn.setShortcut(_translate("Actualization", "Del"))
        self.run_btn.setToolTip(_translate("Actualization", "Запустить чтение"))
        self.run_btn.setText(_translate("Actualization", "Запустить чтение"))
        self.run_btn.setShortcut(_translate("Actualization", "Ctrl+R"))
        self.founded_lbl.setText(_translate("Actualization", "Найденные ГОСТы"))
        self.save_btn.setToolTip(_translate("Actualization", "Сохранить найденные ГОСТы в файл"))
        self.save_btn.setText(_translate("Actualization", "Сохранить"))
        self.save_btn.setShortcut(_translate("Actualization", "Ctrl+S"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.reading_file_tab), _translate("Actualization", "Чтение ГОСТов из файла"))
        self.selenium_tab.setToolTip(_translate("Actualization", "Вкладка для поиска информации о ГОСТах на сайте"))
        self.search_radio_btn.setText(_translate("Actualization", "Из недавнего поиска"))
        self.file_radio_btn.setText(_translate("Actualization", "Из файла"))
        self.choose_btn.setText(_translate("Actualization", "Выбрать файл"))
        self.run_read_btn.setText(_translate("Actualization", "Запустить чтение"))
        self.run_btn_2.setText(_translate("Actualization", "Запустить"))
        self.label_2.setText(_translate("Actualization", "Результат поиска на сайте"))
        self.save_serch_btn.setText(_translate("Actualization", "Сохранить"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.selenium_tab), _translate("Actualization", "Поиск ГОСТов на сайте"))
from . import resoursec_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Actualization = QtWidgets.QMainWindow()
    ui = Ui_Actualization()
    ui.setupUi(Actualization)
    Actualization.show()
    sys.exit(app.exec_())
