# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/not_execute_file_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NotExecuteDialog(object):
    def setupUi(self, NotExecuteDialog):
        NotExecuteDialog.setObjectName("NotExecuteDialog")
        NotExecuteDialog.resize(300, 150)
        NotExecuteDialog.setStyleSheet("* {\n"
"    font-size: 24px;\n"
"    text-align: center;\n"
"    border: 0.5px solid black;\n"
"    border-radius: 10px; \n"
"}\n"
"\n"
"QLabel {\n"
"     qproperty-alignment: AlignCenter; \n"
"    \n"
"}\n"
"\n"
"QWidget {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(8, 4, 188, 255), stop:1 rgba(24, 129, 187, 255));\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: rgba(16, 67, 188, 255);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: rgba(8, 4, 188, 255);\n"
"}\n"
"")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(NotExecuteDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(NotExecuteDialog)
        self.label.setEnabled(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.pushButton = QtWidgets.QPushButton(NotExecuteDialog)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/ChooseItem.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(32, 32))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(NotExecuteDialog)
        QtCore.QMetaObject.connectSlotsByName(NotExecuteDialog)

    def retranslateUi(self, NotExecuteDialog):
        _translate = QtCore.QCoreApplication.translate
        NotExecuteDialog.setWindowTitle(_translate("NotExecuteDialog", "Warning"))
        self.label.setText(_translate("NotExecuteDialog", "Прежде чем запустить,\n"
"выберите файл"))
        self.pushButton.setText(_translate("NotExecuteDialog", "Выбрать файл"))
        self.pushButton.setShortcut(_translate("NotExecuteDialog", "Ctrl+S"))
from . import resoursec_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    NotExecuteDialog = QtWidgets.QDialog()
    ui = Ui_NotExecuteDialog()
    ui.setupUi(NotExecuteDialog)
    NotExecuteDialog.show()
    sys.exit(app.exec_())
