# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/not_founded_for_searc_gialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NotFoundedForSearchDialog(object):
    def setupUi(self, NotFoundedForSearchDialog):
        NotFoundedForSearchDialog.setObjectName("NotFoundedForSearchDialog")
        NotFoundedForSearchDialog.resize(300, 150)
        NotFoundedForSearchDialog.setStyleSheet("* {\n"
"    font-size: 24px;\n"
"    text-align: center;\n"
"    border: 0.5px solid black;\n"
"    border-radius: 10px; \n"
"}\n"
"\n"
"QLabel {\n"
"     qproperty-alignment: AlignCenter; \n"
"    \n"
"}\n"
"\n"
"QTabWidget::pane {\n"
"    top: -1px;\n"
"}\n"
"\n"
"\n"
"QTabWidget::tab-bar {\n"
"    left: 5px;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    color: #bbb;\n"
"    border: 1px solid #444;\n"
"    border-bottom: none;\n"
"    border-top-left-radius: 6px;\n"
"    border-top-right-radius: 6px;\n"
"    padding: 8px 16px;\n"
"    margin-right: 4px;\n"
"}\n"
"\n"
"QTabBar::tab:hover {\n"
"    background: rgba(16, 67, 188, 255);\n"
"    color: #fff;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background: rgba(8, 4, 188, 255);\n"
"    color: #fff;\n"
"    margin-bottom: -1px;\n"
"}\n"
"\n"
"QTabBar::tab:!selected {\n"
"    margin-top: 1px;\n"
"}\n"
"\n"
"QWidget {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(8, 4, 188, 255), stop:1 rgba(24, 129, 187, 255));\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: rgba(16, 67, 188, 255);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: rgba(8, 4, 188, 255);\n"
"}\n"
"")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(NotFoundedForSearchDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(NotFoundedForSearchDialog)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.choose_btn = QtWidgets.QPushButton(NotFoundedForSearchDialog)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/ChooseItem.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.choose_btn.setIcon(icon)
        self.choose_btn.setIconSize(QtCore.QSize(30, 30))
        self.choose_btn.setObjectName("choose_btn")
        self.verticalLayout.addWidget(self.choose_btn)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(NotFoundedForSearchDialog)
        QtCore.QMetaObject.connectSlotsByName(NotFoundedForSearchDialog)

    def retranslateUi(self, NotFoundedForSearchDialog):
        _translate = QtCore.QCoreApplication.translate
        NotFoundedForSearchDialog.setWindowTitle(_translate("NotFoundedForSearchDialog", "Dialog"))
        self.label.setText(_translate("NotFoundedForSearchDialog", "Не найдены данные \n"
"для поиска"))
        self.choose_btn.setText(_translate("NotFoundedForSearchDialog", "Выбрать файл"))
from . import resoursec_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    NotFoundedForSearchDialog = QtWidgets.QDialog()
    ui = Ui_NotFoundedForSearchDialog()
    ui.setupUi(NotFoundedForSearchDialog)
    NotFoundedForSearchDialog.show()
    sys.exit(app.exec_())
