# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/success_read_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_successfully_read(object):
    def setupUi(self, successfully_read):
        successfully_read.setObjectName("successfully_read")
        successfully_read.resize(498, 262)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(successfully_read.sizePolicy().hasHeightForWidth())
        successfully_read.setSizePolicy(sizePolicy)
        successfully_read.setMaximumSize(QtCore.QSize(600, 500))
        successfully_read.setStyleSheet("* {\n"
"    font-size: 24px;\n"
"    text-align: center;\n"
"    border: 0.5px solid black;\n"
"    border-radius: 10px; \n"
"}\n"
"\n"
"QLabel {\n"
"     qproperty-alignment: AlignCenter; \n"
"    \n"
"}\n"
"\n"
"QWidget {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(8, 4, 188, 255), stop:1 rgba(24, 129, 187, 255));\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: rgba(16, 67, 188, 255);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: rgba(8, 4, 188, 255);\n"
"}\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(successfully_read)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(successfully_read)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.save_btn = QtWidgets.QPushButton(successfully_read)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save_btn.sizePolicy().hasHeightForWidth())
        self.save_btn.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/SaveFilled.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.save_btn.setIcon(icon)
        self.save_btn.setIconSize(QtCore.QSize(30, 30))
        self.save_btn.setObjectName("save_btn")
        self.horizontalLayout.addWidget(self.save_btn)
        self.watch_btn = QtWidgets.QPushButton(successfully_read)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.watch_btn.sizePolicy().hasHeightForWidth())
        self.watch_btn.setSizePolicy(sizePolicy)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/Eye.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.watch_btn.setIcon(icon1)
        self.watch_btn.setIconSize(QtCore.QSize(30, 30))
        self.watch_btn.setObjectName("watch_btn")
        self.horizontalLayout.addWidget(self.watch_btn)
        self.to_btn = QtWidgets.QPushButton(successfully_read)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.to_btn.sizePolicy().hasHeightForWidth())
        self.to_btn.setSizePolicy(sizePolicy)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/ChooseItem.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.to_btn.setIcon(icon2)
        self.to_btn.setIconSize(QtCore.QSize(30, 30))
        self.to_btn.setObjectName("to_btn")
        self.horizontalLayout.addWidget(self.to_btn)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(successfully_read)
        QtCore.QMetaObject.connectSlotsByName(successfully_read)

    def retranslateUi(self, successfully_read):
        _translate = QtCore.QCoreApplication.translate
        successfully_read.setWindowTitle(_translate("successfully_read", "Success"))
        self.label.setText(_translate("successfully_read", "Поиск ГОСТов завершен"))
        self.save_btn.setText(_translate("successfully_read", "Сохранить"))
        self.watch_btn.setText(_translate("successfully_read", "Посмотреть"))
        self.to_btn.setText(_translate("successfully_read", "К поиску"))
from . import resoursec_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    successfully_read = QtWidgets.QDialog()
    ui = Ui_successfully_read()
    ui.setupUi(successfully_read)
    successfully_read.show()
    sys.exit(app.exec_())
