# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/warning_execute.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(347, 174)
        Dialog.setStyleSheet("* {\n"
"    font-size: 24px;\n"
"    text-align: center;\n"
"    border: 0.5px solid black;\n"
"    border-radius: 10px; \n"
"}\n"
"\n"
"QLabel {\n"
"     qproperty-alignment: AlignCenter; \n"
"    \n"
"}\n"
"\n"
"QTabWidget::pane {\n"
"    top: -1px;\n"
"}\n"
"\n"
"\n"
"QTabWidget::tab-bar {\n"
"    left: 5px;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    color: #bbb;\n"
"    border: 1px solid #444;\n"
"    border-bottom: none;\n"
"    border-top-left-radius: 6px;\n"
"    border-top-right-radius: 6px;\n"
"    padding: 8px 16px;\n"
"    margin-right: 4px;\n"
"}\n"
"\n"
"QTabBar::tab:hover {\n"
"    background: rgba(16, 67, 188, 255);\n"
"    color: #fff;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background: rgba(8, 4, 188, 255);\n"
"    color: #fff;\n"
"    margin-bottom: -1px;\n"
"}\n"
"\n"
"QTabBar::tab:!selected {\n"
"    margin-top: 1px;\n"
"}\n"
"\n"
"QWidget {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(8, 4, 188, 255), stop:1 rgba(24, 129, 187, 255));\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: rgba(16, 67, 188, 255);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: rgba(8, 4, 188, 255);\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"        background-color: #2e3f6e;\n"
"        color: white;\n"
"        font-weight: bold;\n"
"        padding: 4px;\n"
"        border: 1px solid #6c6c6c;\n"
"    }")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Обработка данных может\n"
"занять много времени,\n"
"также требуется стабильное\n"
"подключение к интернету."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
