name: Build EXE

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write   # нужно для публикации релиза

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt pyinstaller

      - name: Build EXE
        run: |
          pyinstaller --noconsole --onefile main.py

      - name: Upload artifact (for Actions UI)
        uses: actions/upload-artifact@v4
        with:
          name: exe
          path: dist/*.exe

      - name: Get current date
        id: date
        run: echo "date=$(Get-Date -Format 'yyyy-MM-dd-HH-mm')" >> $env:GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.date.outputs.date }}
          name: Release ${{ steps.date.outputs.date }}
          draft: false
          prerelease: false
          files: dist/*.exe
